version: '3.8'

services:
  gleam:
    image: miebach/gleam-docker:gleam1.2.1-elixir1.13.3-erlang24
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: tail -f /dev/null    


